### ISSUE TITLE
siteName Error

### ISSUE THREAD

**Issue by mdaniels-chl** [Kentico/Home#2]
Went through the steps for both Learning Kit and Dancing Goat and both get an error. 
![screen shot 2017-04-05 at 5 11 44 pm](https://cloud.githubusercontent.com/assets/20323862/24729268/00e34cea-1a23-11e7-8018-85973242afb7.png)

**Comment by petrsvihlik** [comment]
I copied your issue to the correct repository: https://github.com/Kentico/Mvc/issues/24
